
spring:
  datasource:
    username: root
    password: mima
    url: jdbc:mysql://192.168.2.134:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true  # sql 显示格式化
  redis:
    host: 192.168.2.134
    database: 0
    pool: 6379
    max-active: 10 #连接池最大连接数（使用负值表示没有限制）
    max-idle: 10 #连接池中的最大空闲连接
    min-idle: 0 #连接池中的最小空闲连接
    max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 5000

  thymeleaf:
    cache: false
    mvc:
      static-path-pattern: /static/**

#  kafka:
#
#    producer:
#      bootstrap-servers: 192.168.2.134:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      bootstrap-servers: 192.168.2.134:9092
#      group-id: seconds-kill
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      topic: hello
#      thread: 3


server:
  port: 8083